baseURL = "http://example.org/"
languageCode = "en-us"
title = "random acts of kindness"
theme = "lithium"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Rules"
    url = "/rules/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/maxheadroom/raok"
[[menu.main]]
    name = "Twitter"
    url = ""

[params]
    description = "random acts of kindness"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
